# Generated by Django 4.0.4 on 2022-11-18 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.CharField(max_length=100)),
                ('set_name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('num_parts', models.IntegerField()),
                ('set_img_url', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('build_completion_date', models.DateField(blank=True, default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
