# Generated by Django 4.0.4 on 2022-11-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='minifigs_num',
            field=models.IntegerField(default=None),
        ),
    ]
