# Generated by Django 4.0.4 on 2022-11-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_minifigs_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='minifigs_num',
            field=models.IntegerField(),
        ),
    ]
