# Generated by Django 4.0.4 on 2022-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_minifigs_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='build_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
